services:
  backend:
    environment:
      # Production-optimized settings
      - LOG_LEVEL=WARN
      - OTLP_DEBUG=false
      - MAXMIND_FALLBACK_ONLINE=false  # Disable online fallback for privacy
      - GOGC=20  # More aggressive garbage collection
      - GOMEMLIMIT=768MiB
    # Don't expose OTLP ports publicly in production
    ports:
      - "3001:3001"  # Only expose API port
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 768M
        reservations:
          cpus: '0.3'
          memory: 192M
      # Production restart policy
      restart_policy:
        condition: unless-stopped
        delay: 5s
        max_attempts: 3
        window: 120s

  frontend:
    environment:
      - NODE_ENV=production
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
      restart_policy:
        condition: unless-stopped
        delay: 5s
        max_attempts: 3
        window: 120s

  # Disable sample app and traffic generator in production
  sample-app:
    profiles:
      - disabled

  traffic-generator:
    profiles:
      - disabled

  # Ensure MaxMind updater runs regularly in production
  maxmind-updater:
    restart: "no"  # Run once on startup